---
python_versions:
    - "3.13.1"

global_python_version: "3.13.1"

# Path where pyenv will be installed
pyenv_root: "{{ ansible_env.HOME }}/.pyenv"

# List of dependencies required for building Python
pyenv_dependencies:
    - gcc
    - make
    - openssl-devel
    - tk-devel
    - xz-devel
    - sqlite-devel
    - readline-devel
    - curl
    - wget
